language: node_js

node_js:
  - 14

install:
  - cd core; yarn link; cd -; yarn link domoja-core
  - for m in proxiti tempo; do cd modules/$m; yarn link; cd -; yarn link domoja-$m; done
  - yarn install --frozen-lockfile

after_success:
- npm run coverage

