# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Install core
      run: cd core; yarn; yarn link; cd -; yarn link domoja-core
    - name: Install modules
      run: for m in proxiti tempo; do cd modules/$m; yarn; yarn link; cd -; yarn link domoja-$m; done
    - name: yarn install  
      run: yarn install --frozen-lockfile
    - name: Run tests
      run: yarn run test
    - name: Generate report
      run: yarn run prepare:report
      
    - name: Coveralls 
      uses: coverallsapp/github-action@master
      with:
        flag-name: run-${{ matrix.node-version }}
        parallel: true
        github-token: ${{ secrets.github_token }}

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
